# Generated by Django 3.0.4 on 2022-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
            options={
                'db_table': 'notices',
            },
        ),
    ]
