# Generated by Django 3.0.4 on 2022-06-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notices',
            table=None,
        ),
    ]
